name = "pokefetch"
compatibility_date = "2024-10-01"
assets = { directory = "dist" }

[vars]  
POKEAPI_BASE_URL = "https://pokeapi.co/api/v2"

[env.production.vars]
POKEAPI_BASE_URL = "https://pokeapi.co/api/v2"